### ISSUE TITLE
The site is down

### ISSUE THREAD

**Issue by Kosai106** [blitz-js/versions-diff-web#2]
# Bug

```zsh
Uncaught SyntaxError: Unexpected token '<'
```

## Steps to reproduce

1. Visit http://versions-diff-web.vercel.app/

Describe what you expected to happen:

1. The site loads

**Comment by flybayer** [comment]
The site has never been up 😅  Waiting for someone to fix it

**Comment by Kosai106** [comment]
@flybayer Oh! I thought I had seen it online before. 😅
